{"name": "test_register_user_variants[case0]", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http://localhost:8000/api/v1/management/auth/register", "trace": "case = {'email': 'use2@example.com', 'expected_error_code': None, 'expected_status': 201, 'password': 'StrongPass456!'}\n\n    @pytest.mark.parametrize(\"case\", get_case_by_index(\"register_user\", index=0))\n    def test_register_user_variants(case):\n        user = ManagementUserCreate(email=case[\"email\"], password=case[\"password\"])\n>       response = api.register_user(user)\n\ntest_api.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\utils\\api_helper.py:22: in register_user\n    resp.raise_for_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Response [409]>\n\n    def raise_for_status(self):\n        \"\"\"Raises :class:`HTTPError`, if one occurred.\"\"\"\n    \n        http_error_msg = \"\"\n        if isinstance(self.reason, bytes):\n            # We attempt to decode utf-8 first because some servers\n            # choose to localize their reason strings. If the string\n            # isn't utf-8, we fall back to iso-8859-1 for all other\n            # encodings. (See PR #3538)\n            try:\n                reason = self.reason.decode(\"utf-8\")\n            except UnicodeDecodeError:\n                reason = self.reason.decode(\"iso-8859-1\")\n        else:\n            reason = self.reason\n    \n        if 400 <= self.status_code < 500:\n            http_error_msg = (\n                f\"{self.status_code} Client Error: {reason} for url: {self.url}\"\n            )\n    \n        elif 500 <= self.status_code < 600:\n            http_error_msg = (\n                f\"{self.status_code} Server Error: {reason} for url: {self.url}\"\n            )\n    \n        if http_error_msg:\n>           raise HTTPError(http_error_msg, response=self)\nE           requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http://localhost:8000/api/v1/management/auth/register\n\n..\\.venv\\lib\\site-packages\\requests\\models.py:1026: HTTPError"}, "parameters": [{"name": "case", "value": "{'email': 'use2@example.com', 'password': 'StrongPass456!', 'expected_status': 201, 'expected_error_code': None}"}], "start": 1753697229376, "stop": 1753697231555, "uuid": "8d761978-9dd4-42d6-b58d-738e542ce866", "historyId": "19b20baa8262f8dc42b709d0f855ca61", "testCaseId": "f08836675e974b4c1563abef49b1b707", "fullName": "tests.test_api#test_register_user_variants", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "23348-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}], "titlePath": ["tests", "test_api.py"]}