{"name": "test_forgot_password", "status": "failed", "statusDetails": {"message": "AssertionError: <Response [404]> is not an instance of <class 'dict'>", "trace": "self = <management_user.TestManagementUserAuth testMethod=test_forgot_password>\n\n    def test_forgot_password(self):\n        case = self.test_data[\"forgot_password\"][0]\n        response = self.api.forgot_password(email=case[\"email\"])\n>       self.assertIsInstance(response, dict)\nE       AssertionError: <Response [404]> is not an instance of <class 'dict'>\n\nmanagement_user.py:56: AssertionError"}, "start": 1754043629131, "stop": 1754043630782, "uuid": "c5a7547b-f572-4a44-9c41-028ae85f5e3f", "historyId": "3bb328547a091bc0bf228796dc8a14db", "testCaseId": "3bb328547a091bc0bf228796dc8a14db", "fullName": "tests.management_user.TestManagementUserAuth#test_forgot_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "8388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}