{"name": "test_forgot_password", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8000/api/v1/management/auth/forgot-password", "trace": "self = <management_user.TestManagementUserAuth testMethod=test_forgot_password>\n\n    def test_forgot_password(self):\n        case = self.test_data[\"forgot_password\"][0]\n>       response = self.api.forgot_password(email=case[\"email\"])\n\nmanagement_user.py:55: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\utils\\api_helper1.py:91: in forgot_password\n    resp = self.post(endpoint, json={\"email\": email})\n..\\utils\\api_client.py:76: in post\n    return self._handle_response(resp)\n..\\utils\\api_client.py:51: in _handle_response\n    response.raise_for_status()  # Raises HTTPError for bad status codes\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Response [404]>\n\n    def raise_for_status(self):\n        \"\"\"Raises :class:`HTTPError`, if one occurred.\"\"\"\n    \n        http_error_msg = \"\"\n        if isinstance(self.reason, bytes):\n            # We attempt to decode utf-8 first because some servers\n            # choose to localize their reason strings. If the string\n            # isn't utf-8, we fall back to iso-8859-1 for all other\n            # encodings. (See PR #3538)\n            try:\n                reason = self.reason.decode(\"utf-8\")\n            except UnicodeDecodeError:\n                reason = self.reason.decode(\"iso-8859-1\")\n        else:\n            reason = self.reason\n    \n        if 400 <= self.status_code < 500:\n            http_error_msg = (\n                f\"{self.status_code} Client Error: {reason} for url: {self.url}\"\n            )\n    \n        elif 500 <= self.status_code < 600:\n            http_error_msg = (\n                f\"{self.status_code} Server Error: {reason} for url: {self.url}\"\n            )\n    \n        if http_error_msg:\n>           raise HTTPError(http_error_msg, response=self)\nE           requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8000/api/v1/management/auth/forgot-password\n\n..\\.venv\\lib\\site-packages\\requests\\models.py:1026: HTTPError"}, "attachments": [{"name": "log", "source": "a84d3c9f-27fb-4351-965a-23eb601eac96-attachment.txt", "type": "text/plain"}], "start": 1754044030326, "stop": 1754044030493, "uuid": "e24d7b89-5694-4247-90a0-540d3c8707d9", "historyId": "3bb328547a091bc0bf228796dc8a14db", "testCaseId": "3bb328547a091bc0bf228796dc8a14db", "fullName": "tests.management_user.TestManagementUserAuth#test_forgot_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "12092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}