{"name": "test_verify_gym_email", "status": "failed", "statusDetails": {"message": "AssertionError: Verify gym email test failed: 'dict' object has no attribute 'status_code'", "trace": "self = <test_gym_management.TestGymManagement testMethod=test_verify_gym_email>\n\n    def test_verify_gym_email(self):\n        \"\"\"Test verifying gym user's email using token.\"\"\"\n        try:\n            token = self.test_data[\"verify_gym_email\"][0][\"token\"]\n>           response = self.api.verify_gym_email(token=token)\n\ntest_gym_management.py:112: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <utils.api_helper1.ManagementUserAPIHandler object at 0x0000021431876C20>\ntoken = 'pFMoaA2baeKnkBEAyd5ul1P2YfxSXNPR78szaUyqumX73paRGPxiFD11BDSfz8LLicWdZiAlPECXzNXUezWeYQ'\n\n    def verify_gym_email(self, token: str):\n        \"\"\"\n        Verify gym user email using a token.\n        \"\"\"\n        endpoint = f\"/api/{self.api_version}/gym/auth/verify-email\"\n        params = {\"token\": token}\n        log.info(f\"Verifying gym user email | Endpoint: {endpoint} | Params: {params}\")\n        try:\n            resp = self.get(endpoint, params=params)\n>           log.info(f\"Verify gym email response | Status: {resp.status_code}\")\nE           AttributeError: 'dict' object has no attribute 'status_code'\n\n..\\utils\\api_helper1.py:791: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_gym_management.TestGymManagement testMethod=test_verify_gym_email>\n\n    def test_verify_gym_email(self):\n        \"\"\"Test verifying gym user's email using token.\"\"\"\n        try:\n            token = self.test_data[\"verify_gym_email\"][0][\"token\"]\n            response = self.api.verify_gym_email(token=token)\n            self.assertIn(\"message\", response)\n        except Exception as e:\n>           self.fail(f\"Verify gym email test failed: {e}\")\nE           AssertionError: Verify gym email test failed: 'dict' object has no attribute 'status_code'\n\ntest_gym_management.py:115: AssertionError"}, "description": "Test verifying gym user's email using token.", "attachments": [{"name": "log", "source": "7af3a8ae-3a21-4125-970c-e2c606c70308-attachment.txt", "type": "text/plain"}], "start": 1754321286768, "stop": 1754321369795, "uuid": "d4f0f97b-be1c-49fb-8661-935cbd2f7e12", "historyId": "882182fd8ba85884ddc4dcb8a7c31ee8", "testCaseId": "882182fd8ba85884ddc4dcb8a7c31ee8", "fullName": "tests.test_gym_management.TestGymManagement#test_verify_gym_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_gym_management"}, {"name": "subSuite", "value": "TestGymManagement"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "11216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_gym_management"}], "titlePath": ["tests", "test_gym_management.py", "TestGymManagement"]}