{"uuid": "1d5cbb68-2027-4ab7-b634-22ab1835dfa7", "children": ["b2e7a268-e5e9-4edc-bcab-7055e59bd4ca"], "befores": [{"name": "auth_tokens", "status": "failed", "statusDetails": {"message": "Failed: Login fixture setup failed: 401 Client Error: Unauthorized for url: http://localhost:8000/api/v1/management/auth/login\n", "trace": "  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\tests\\conftest.py\", line 54, in auth_tokens\n    pytest.fail(f\"Login fixture setup failed: {e}\")\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754389093975, "stop": 1754389094025}], "start": 1754389093974, "stop": 1754389094221}