{"name": "test_logout_user", "status": "failed", "statusDetails": {"message": "AssertionError: <Response [401]> is not an instance of <class 'dict'>", "trace": "self = <management_user.TestManagementUserAuth testMethod=test_logout_user>\n\n    def test_logout_user(self):\n        response = self.api.logout_user(token=self.access_token)\n>       self.assertIsInstance(response, dict)\nE       AssertionError: <Response [401]> is not an instance of <class 'dict'>\n\nmanagement_user.py:122: AssertionError"}, "start": 1754043680338, "stop": 1754043680385, "uuid": "5d495ba7-c765-422c-957e-0339e57b75f7", "historyId": "2325129a7d5de88b0612c3d240736c0b", "testCaseId": "2325129a7d5de88b0612c3d240736c0b", "fullName": "tests.management_user.TestManagementUserAuth#test_logout_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "17124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}