{"name": "test_create_gym_user", "status": "failed", "statusDetails": {"message": "AssertionError: Create gym user test failed: 'dict' object has no attribute 'status_code'", "trace": "self = <test_gym_management.TestGymManagement testMethod=test_create_gym_user>\n\n    def test_create_gym_user(self):\n        \"\"\"Test registering a new gym user.\"\"\"\n        try:\n            user_data = self.test_data[\"create_gym_user\"][0]\n>           response = self.api.create_gym_user(user_data=user_data)\n\ntest_gym_management.py:104: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <utils.api_helper1.ManagementUserAPIHandler object at 0x000001E407F5C0D0>\nuser_data = {'cpassword': 'SecurePass123!', 'email': 'john1.doe@example.com', 'first_name': 'John', 'last_name': 'Doe', ...}\n\n    def create_gym_user(self, user_data: dict):\n        \"\"\"\n        Register a new gym user.\n        \"\"\"\n        endpoint = f\"/api/{self.api_version}/gym/auth/register\"\n        log.info(f\"Registering gym user | Endpoint: {endpoint} | Payload: {user_data}\")\n        try:\n            resp = self.post(endpoint, json=user_data)\n>           log.info(f\"Create gym user response | Status: {resp.status_code}\")\nE           AttributeError: 'dict' object has no attribute 'status_code'\n\n..\\utils\\api_helper1.py:776: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_gym_management.TestGymManagement testMethod=test_create_gym_user>\n\n    def test_create_gym_user(self):\n        \"\"\"Test registering a new gym user.\"\"\"\n        try:\n            user_data = self.test_data[\"create_gym_user\"][0]\n            response = self.api.create_gym_user(user_data=user_data)\n            self.assertIn(\"data\", response)\n            TestGymManagement.gym_user_id = response[\"data\"][\"id\"]\n        except Exception as e:\n>           self.fail(f\"Create gym user test failed: {e}\")\nE           AssertionError: Create gym user test failed: 'dict' object has no attribute 'status_code'\n\ntest_gym_management.py:108: AssertionError"}, "description": "Test registering a new gym user.", "attachments": [{"name": "log", "source": "529a8f2e-6f60-49b1-bf47-d02372c00391-attachment.txt", "type": "text/plain"}], "start": 1754320474904, "stop": 1754320476143, "uuid": "4dfa74e5-6104-4448-aa64-b52d79be8c64", "historyId": "cbcdd1be7559b52367ead9a617a78e0c", "testCaseId": "cbcdd1be7559b52367ead9a617a78e0c", "fullName": "tests.test_gym_management.TestGymManagement#test_create_gym_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_gym_management"}, {"name": "subSuite", "value": "TestGymManagement"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "1576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_gym_management"}], "titlePath": ["tests", "test_gym_management.py", "TestGymManagement"]}