{"name": "test_logout_user", "status": "failed", "statusDetails": {"message": "AssertionError: <Response [401]> is not an instance of <class 'dict'>", "trace": "self = <management_user.TestManagementUserAuth testMethod=test_logout_user>\n\n    def test_logout_user(self):\n        response = self.api.logout_user(token=self.access_token)\n>       self.assertIsInstance(response, dict)\nE       AssertionError: <Response [401]> is not an instance of <class 'dict'>\n\nmanagement_user.py:122: AssertionError"}, "start": 1754043631264, "stop": 1754043631310, "uuid": "a6108dd0-8d94-4f83-85d8-9af72ab3d559", "historyId": "2325129a7d5de88b0612c3d240736c0b", "testCaseId": "2325129a7d5de88b0612c3d240736c0b", "fullName": "tests.management_user.TestManagementUserAuth#test_logout_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "8388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}