{"name": "test_get_user_by_id", "status": "failed", "statusDetails": {"message": "AssertionError: unexpectedly None", "trace": "self = <management_user.TestManagementUserAuth testMethod=test_get_user_by_id>\n\n    def test_get_user_by_id(self):\n>       self.assertIsNotNone(self.user_id)\nE       AssertionError: unexpectedly None\n\nmanagement_user.py:99: AssertionError"}, "start": 1754043630955, "stop": 1754043630956, "uuid": "76677de1-6c7e-40c5-aa5c-1daf0184e36f", "historyId": "c74391dc0149f166a4375d1eace4baa7", "testCaseId": "c74391dc0149f166a4375d1eace4baa7", "fullName": "tests.management_user.TestManagementUserAuth#test_get_user_by_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "8388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}