{"uuid": "7de13e15-b461-4275-8889-c8840e7d4cb4", "children": ["7b32dd3d-ae7b-4069-8dd4-1547d0b1ae7e"], "befores": [{"name": "auth_tokens", "status": "failed", "statusDetails": {"message": "Failed: Login fixture setup failed: 401 Client Error: Unauthorized for url: http://localhost:8000/api/v1/management/auth/login\n", "trace": "  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\tests\\conftest.py\", line 54, in auth_tokens\n    pytest.fail(f\"Login fixture setup failed: {e}\")\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754388700816, "stop": 1754388700912}], "start": 1754388700816, "stop": 1754388701132}